services:
  genkitxollama:
    image: genkitxollama
    build:
      context: node_modules/genkitx-ollama
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
