services:
  nodehtmlparser:
    image: nodehtmlparser
    build:
      context: node_modules/node-html-parser
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
